/*
**    KALC POS  - Open Source Point of Sale
**
**    Copyright (c) 2015-2023 KALC Corporation   
**
**    http://kalcapps.com/enterprise
**   
**    (at your option) any later version.
**
**    KALC POS is distributed under proprietary license.
**    but WITHOUT ANY WARRANTY; without even the implied warranty of
**    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**
**
*/


package ke.kalc.pos.forms;

import java.awt.Component;
import javax.swing.JComponent;
import javax.swing.JPanel;
import ke.kalc.basic.BasicException;

public class JPanelMenu extends JPanel implements JPanelView {

    private MenuDefinition m_menu;
    private boolean created = false;

    /**
     * Creates new form JStockMenu
     *
     * @param menu
     */
    public JPanelMenu(MenuDefinition menu) {

        m_menu = menu;
        created = false;

        initComponents();
    }

    /**
     *
     * @return
     */
    @Override
    public JComponent getComponent() {
        return this;
    }

    /**
     *
     * @return
     */
    @Override
    public String getTitle() {
        return m_menu.getTitle();
    }

    /**
     *
     * @throws BasicException
     */
    @Override
    public void activate() throws BasicException {

        if (created == false) {

            for (int i = 0; i < m_menu.countMenuElements(); i++) {
                MenuElement menuitem = m_menu.getMenuElement(i);
                menuitem.addComponent(this);
            }
            created = true;
        }
    }

    /**
     *
     * @return
     */
    @Override
    public boolean deactivate() {
        return true;
    }

    /**
     *
     * @param title
     */
    public void addTitle(Component title) {

        currententrypanel = null;

        JPanel titlepanel = new JPanel();
        titlepanel.setLayout(new java.awt.BorderLayout());
        titlepanel.add(title, java.awt.BorderLayout.CENTER);
        titlepanel.applyComponentOrientation(getComponentOrientation());

        menucontainer.add(titlepanel);
    }

    /**
     *
     * @param entry
     */
    public void addEntry(Component entry) {

        if (currententrypanel == null) {
            currententrypanel = new JPanel();
            currententrypanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 0));
            currententrypanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
            menucontainer.add(currententrypanel);
        }

        currententrypanel.add(entry);
        currententrypanel.applyComponentOrientation(getComponentOrientation());

    }

    private JPanel currententrypanel = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menucontainer = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setFont(KALCFonts.DEFAULTFONT
        );
        setLayout(new java.awt.BorderLayout());

        menucontainer.setLayout(new javax.swing.BoxLayout(menucontainer, javax.swing.BoxLayout.Y_AXIS));
        add(menucontainer, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel menucontainer;
    // End of variables declaration//GEN-END:variables

}
